services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "12453:12453"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/metacraft?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: metacraft
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_MONGODB_HOST: mongodb
    volumes:
      - ./src/main/resources:/app/src/main/resources:ro
    networks:
      - default

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: metacraft
      MYSQL_USER: metacraft
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: